In [1]:
## Importing Lib's
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentence
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Defining Vocabulary Size 
voc_size = 10000

In [5]:
## One Hot Representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[3721, 3672, 6450, 6884],
 [3721, 3672, 6450, 3],
 [3721, 8380, 6450, 7698],
 [8884, 8520, 2222, 1180, 8557],
 [8884, 8520, 2222, 1180, 8501],
 [5660, 3721, 3557, 6450, 5414],
 [8218, 3592, 8343, 1180]]

In [9]:
##  Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3721 3672 6450 6884]
 [   0    0    0    0 3721 3672 6450    3]
 [   0    0    0    0 3721 8380 6450 7698]
 [   0    0    0 8884 8520 2222 1180 8557]
 [   0    0    0 8884 8520 2222 1180 8501]
 [   0    0    0 5660 3721 3557 6450 5414]
 [   0    0    0    0 8218 3592 8343 1180]]


In [11]:
## Feature Representation
dim = 10
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile('adam','mse')
model.summary()

d:\Projects\Simple RNN Movies Review (IMDB)\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[-0.00073578,  0.04388392, -0.01813886, -0.01466339,
         -0.03756964,  0.04954093, -0.01508986,  0.0102759 ,
          0.04597289, -0.0285732 ],
        [-0.00073578,  0.04388392, -0.01813886, -0.01466339,
         -0.03756964,  0.04954093, -0.01508986,  0.0102759 ,
          0.04597289, -0.0285732 ],
        [-0.00073578,  0.04388392, -0.01813886, -0.01466339,
         -0.03756964,  0.04954093, -0.01508986,  0.0102759 ,
          0.04597289, -0.0285732 ],
        [-0.00073578,  0.04388392, -0.01813886, -0.01466339,
         -0.03756964,  0.04954093, -0.01508986,  0.0102759 ,
          0.04597289, -0.0285732 ],
        [-0.04398065,  0.0478673 ,  0.00368836,  0.00070176,
          0.0359501 ,  0.01186603, -0.03380515,  0.02037213,
          0.01204078,  0.03569199],
        [-0.02605753, -0.04559983,  0.00937468, -0.02384019,
         -0.00566634,  0.01682521, -0.01680381,  0.01971311,
         -0.0190238 , -0.0266149 ],
        [-0.03782951, -0.02559153,  0.0247103 , -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 3721, 3672, 6450, 6884], dtype=int32)